import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const downloadReport = (data) => {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(22);
  doc.setTextColor(30, 144, 255);
  doc.text("AI Resume Analysis Report", 20, 20);

  // Date
  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 30);

  // ATS Score
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text(`ATS Score: ${data.ats_score}/100`, 20, 45);

  doc.text(`Rating: ${data.rating}`, 20, 55);

  // Summary Table
  autoTable(doc, {
    startY: 65,
    head: [["Category", "Value"]],
    body: [
      ["Skills Found", data.skills_found],
      ["Experience", data.experience],
      ["Education", data.education],
      ["Overall Rating", data.rating],
    ],
  });

  // Strengths
  let y = doc.lastAutoTable.finalY + 15;

  doc.setFontSize(15);
  doc.text("Strengths", 20, y);

  y += 8;

  data.strengths.forEach((item) => {
    doc.text("• " + item, 25, y);
    y += 7;
  });

  // Weaknesses
  y += 8;
  doc.text("Weaknesses", 20, y);

  y += 8;

  data.weaknesses.forEach((item) => {
    doc.text("• " + item, 25, y);
    y += 7;
  });

  // Missing Skills
  y += 8;
  doc.text("Missing Skills", 20, y);

  y += 8;

  data.missing_skills.forEach((item) => {
    doc.text("• " + item, 25, y);
    y += 7;
  });

  // Suggestions
  y += 8;
  doc.text("Suggestions", 20, y);

  y += 8;

  data.suggestions.forEach((item) => {
    doc.text("• " + item, 25, y);
    y += 7;
  });

  // Footer
  doc.setFontSize(11);
  doc.setTextColor(120);
  doc.text(
    "Generated by AI Resume Analyzer",
    20,
    285
  );

  doc.save("AI_Resume_Report.pdf");
};